name: pr merge

on:
  workflow_call:
    inputs:  
      autoMerge:
        description: 'Auto merge pr'
        default: true
        required: false
        type: boolean
    secrets:
      CI_PAT_PR:
        required: true
jobs:
  auto-merge:
    if: ${{ inputs.autoMerge }}
    uses: ./.github/workflows/common-pr-auto-merge.yml
    secrets: inherit