name: release

on:
  workflow_call:

jobs:
  docker:
    uses: ./.github/workflows/common-docker-release.yaml
    secrets: inherit
    with:
      releaseImageTag: '{{ .Version }}-jvm'
      tags: '{{ .Release }}-jvm'
  native:
    uses: ./.github/workflows/common-docker-release.yaml
    secrets: inherit
  release:
    uses: ./.github/workflows/common-github-release.yml
    secrets: inherit
